spring:
  application:
    name: hik-isup

server:
  port: 16233
  address: 0.0.0.0

hik:
  platform:
    pushAddress: ${FLOW_APP_PUSH_ADDRESS:http://127.0.0.1:9080/iot/event/HK/callback}
    ttsServer: ${FLOW_TTS_SERVER:http://127.0.0.1:3000/api/v1/tts/generateJson}

  stream:
    isSSL: false
    domain: __defaultVhost__
    http:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_STREAM_HTTP_PORT:7788}

  isup:
    cmsServer:
      ip: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      port: ${FLOW_HIK_CMS_PORT:7660}

    dasServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_DAS_PORT:7660}

    smsServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_SMS_PORT:7665}
      listenIp: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      listenPort: ${FLOW_HIK_SMS_LISTEN_PORT:7665}

    smsBackServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_SMS_BACK_PORT:8000}
      listenIp: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      listenPort: ${FLOW_HIK_SMS_BACK_LISTEN_PORT:8000}

    voiceSmsServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_VOICE_SMS_PORT:7500}
      listenIp: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      listenPort: ${FLOW_HIK_VOICE_SMS_LISTEN_PORT:7500}

    alarmServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      tcpPort: ${FLOW_HIK_ALARM_TCP_PORT:7663}
      udpPort: ${FLOW_HIK_ALARM_UDP_PORT:7662}
      type: ${FLOW_HIK_ALARM_TYPE:2}
      listenIp: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      listenTcpPort: ${FLOW_HIK_ALARM_LISTEN_TCP_PORT:7663}
      listenUdpPort: ${FLOW_HIK_ALARM_LISTEN_UDP_PORT:7662}

    picServer:
      ip: ${FLOW_HIK_PUBLIC_IP:104.248.187.45}
      port: ${FLOW_HIK_PIC_PORT:6120}
      type: ${FLOW_HIK_PIC_TYPE:2}
      listenIp: ${FLOW_HIK_LISTEN_IP:104.248.187.45}
      listenPort: ${FLOW_HIK_PIC_LISTEN_PORT:6120}

    isupKey: ${FLOW_HIK_ISUP_KEY:hik12345}
    eventInfoPrintType: ${FLOW_HIK_EVENT_PRINT_TYPE:console}